server:
  port: 8002

rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: short-link_project-service_stats-save_pg
    topic: short-link_project-service_topic
    send-message-timeout: 2000
    retry-times-when-send-failed: 1
    retry-times-when-send-async-failed: 1
  consumer:
    group: short-link_project-service_stats-save_cg

spring:
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
  application:
    name: short-link-project
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
#    listener:
#      simple:
#        acknowledge-mode: manual
  mvc:
    view:
      prefix: /templates/
      suffix: .html
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:shardingsphere-config.yaml
  data:
    redis:
      port: 6379
      host: localhost
      password: 198311

short-link:
  default-domain: nurl.ink
  api:
    locale-stats:
      key: 0e2e5f430fddf36b5645edee727c1905


