server:
  port: 8002

spring:
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
  application:
    name: short-link-project
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        acknowledge-mode: manual

  mvc:
    view:
      prefix: /templates/
      suffix: .html
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:shardingsphere-config.yaml
  data:
    redis:
      port: 6379
      host: localhost
      password: 198311

short-link:
  default-domain: nurl.ink
  api:
    locale-stats:
      key: 0e2e5f430fddf36b5645edee727c1905


